name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@5e13dcb03778dc9a47bd0adbd84c48392b32cd46
    with:
      sonarOrganization: gridsuite
      sonarProjectKey: org.gridsuite:actions-server
      dockerImage: docker.io/gridsuite/actions-server
      dockerUsername: gridsuiteci
      eventType: actions_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
