name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-generic.yml@v1
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      sonarOrganization: ${{ vars.SONAR_ORGANIZATION }}
      sonarProjectKey: ${{ vars.SONAR_PROJECT_KEY }}
      dockerImage: ${{ vars.DOCKER_IMAGE }}
      dockerUsername: ${{ vars.DOCKER_USERNAME }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
